import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/localization/app_localizations.dart';
import '../../data/models/currency.dart';
import '../../data/models/models.dart';
import '../providers/app_state.dart';
import 'person_screen.dart';
class HomeScreen extends StatefulWidget{const HomeScreen({super.key});@override State<HomeScreen> createState()=>_HomeScreenState();}
class _HomeScreenState extends State<HomeScreen>{int tab=0;final search=TextEditingController();@override Widget build(BuildContext context){final l=AppLocalizations.of(context);return Consumer<AppState>(builder:(c,s,_){return Scaffold(appBar:AppBar(title:Text(l.t(['home','accounts','transactions','reports','settings'][tab])),actions:[if(tab==0)IconButton(onPressed:()=>showSearch(context,delegate:AccountSearch(s)),icon:const Icon(Icons.search)),PopupMenuButton<Ledger>(onSelected:s.selectLedger,itemBuilder:(_)=>s.ledgers.map((x)=>PopupMenuItem(value:x,child:Text('${x.name} (${x.currencyCode})'))).toList())]),body:[_dashboard(context,s,l),_accounts(context,s,l),_transactions(context,s,l),_reports(context,s,l),_settings(context,s,l)][tab],floatingActionButton:tab<2?FloatingActionButton(onPressed:()=>_add(context,s,l),child:const Icon(Icons.add)):null,bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:[NavigationDestination(icon:const Icon(Icons.dashboard_outlined),label:l.t('home')),NavigationDestination(icon:const Icon(Icons.people_outline),label:l.t('accounts')),NavigationDestination(icon:const Icon(Icons.receipt_long_outlined),label:l.t('transactions')),NavigationDestination(icon:const Icon(Icons.bar_chart),label:l.t('reports')),NavigationDestination(icon:const Icon(Icons.settings_outlined),label:l.t('settings'))]);});}
Widget _dashboard(BuildContext c,AppState s,AppLocalizations l)=>RefreshIndicator(onRefresh:s.refresh,child:ListView(padding:const EdgeInsets.all(16),children:[if(s.currentLedger!=null)Card(child:ListTile(leading:const Icon(Icons.book),title:Text(s.currentLedger!.name),subtitle:Text(s.currentLedger!.currencyCode))),GridView.count(shrinkWrap:true,crossAxisCount:2,childAspectRatio:1.7,children:[_stat(l.t('totalReceivable'),s.totals['receivable']!,Colors.green,l),_stat(l.t('totalPayable'),s.totals['payable']!,Colors.orange,l),_stat(l.t('net'),s.totals['net']!,s.totals['net']!>=0?Colors.blue:Colors.red,l),_stat(l.t('accounts'),s.people.length.toDouble(),Colors.teal,l)]),Padding(padding:const EdgeInsets.only(top:20),child:Text(l.t('recent'),style:Theme.of(c).textTheme.titleLarge)),...s.tx.take(8).map((x)=>ListTile(leading:Icon(x.type=='receivable'||x.type=='received'?Icons.arrow_upward:Icons.arrow_downward),title:Text(x.description.isEmpty?x.type:x.description),subtitle:Text(l.date(x.date)),trailing:Text(l.money(x.amount,s.currentLedger!.currencyCode,CurrencyCatalog.byCode(s.currentLedger!.currencyCode).decimalDigits))))]));
Widget _stat(String title,double value,Color color,AppLocalizations l)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title),const Spacer(),Text(value.toStringAsFixed(0),style:TextStyle(fontSize:20,fontWeight:FontWeight.bold,color:color))])));
Widget _accounts(BuildContext c,AppState s,AppLocalizations l)=>ListView(padding:const EdgeInsets.all(12),children:[...s.people.map((p)=>FutureBuilder<Map<String,double>>(future:s.database.totals(s.currentLedger!.id!,personId:p.id),builder:(c,x){final n=x.data?['net']??0;return Card(child:ListTile(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>PersonScreen(person:p))),leading:CircleAvatar(child:Text(p.name.characters.first)),title:Text(p.name),subtitle:Text(p.phone.isEmpty?l.t('balance'):p.phone),trailing:Text(l.money(n,s.currentLedger!.currencyCode,CurrencyCatalog.byCode(s.currentLedger!.currencyCode).decimalDigits),style:TextStyle(color:n>=0?Colors.green:Colors.red,fontWeight:FontWeight.bold)));}))]);
Widget _transactions(BuildContext c,AppState s,AppLocalizations l)=>ListView(padding:const EdgeInsets.all(12),children:[TextField(controller:search,onChanged:(v){s.search=v;s.refresh();},decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:l.t('search'))),...s.tx.map((x)=>ListTile(title:Text(x.description.isEmpty?x.type:x.description),subtitle:Text('${l.date(x.date)} • ${x.category}'),trailing:Text(l.money(x.amount,s.currentLedger!.currencyCode,CurrencyCatalog.byCode(s.currentLedger!.currencyCode).decimalDigits)),onLongPress:()=>showDialog(context:c,builder:(_)=>AlertDialog(title:Text(l.t('confirmDelete')),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:Text(l.t('cancel'))),FilledButton(onPressed:(){s.removeTx(x.id!);Navigator.pop(c);},child:Text(l.t('delete')))]))) ]);
Widget _reports(BuildContext c,AppState s,AppLocalizations l)=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Text(l.t('reportsSoon'),textAlign:TextAlign.center)));
Widget _settings(BuildContext c,AppState s,AppLocalizations l)=>ListView(children:[ListTile(title:Text(l.t('ledgers')),leading:const Icon(Icons.book),onTap:()=>_newLedger(c,s,l)),ListTile(title:Text(l.t('language')),leading:const Icon(Icons.language),subtitle:Text('العربية / English')),ListTile(title:Text(l.t('theme')),leading:const Icon(Icons.dark_mode)),ListTile(title:Text('Backup / Restore'),leading:const Icon(Icons.backup),onTap:()async{final data=await s.database.exportJson();if(c.mounted)showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('Backup'),content:SelectableText(data.substring(0,data.length>500?500:data.length)),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:Text(l.t('cancel')))]);})]);
Future<void> _add(BuildContext c,AppState s,AppLocalizations l)async{if(tab==1){await Navigator.push(c,MaterialPageRoute(builder:(_)=>PersonForm(ledgerId:s.currentLedger!.id!,onSave:s.addPerson)));}else{final p=s.people.isEmpty?null:s.people.first;if(p!=null)await showTransactionForm(c,s,p,l);else ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(l.t('noData'))));}}
Future<void> _newLedger(BuildContext c,AppState s,AppLocalizations l)async{final n=TextEditingController();String cur='YER';await showDialog(context:c,builder:(_)=>AlertDialog(title:Text(l.t('ledger')),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:InputDecoration(labelText:l.t('name'))),DropdownButtonFormField(value:cur,items:CurrencyCatalog.all.map((x)=>DropdownMenuItem(value:x.code,child:Text('${x.code} - ${x.name(l.isArabic)}'))).toList(),onChanged:(v)=>cur=v!)]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:Text(l.t('cancel'))),FilledButton(onPressed:(){if(n.text.trim().isNotEmpty)s.addLedger(n.text.trim(),cur);Navigator.pop(c);},child:Text(l.t('save')))]));}
}
class AccountSearch extends SearchDelegate{final AppState s;AccountSearch(this.s);@override List<Widget>? buildActions(c)=>[IconButton(onPressed:()=>query='',icon:const Icon(Icons.clear))];@override Widget buildLeading(c)=>BackButton(onPressed:()=>close(c,null));@override Widget buildResults(c)=>ListView(children:s.people.where((p)=>p.name.toLowerCase().contains(query.toLowerCase())||p.phone.contains(query)).map((p)=>ListTile(title:Text(p.name),subtitle:Text(p.phone))).toList());@override Widget buildSuggestions(c)=>buildResults(c);}
