import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/localization/app_localizations.dart';
import '../../data/models/currency.dart';
import '../../data/models/models.dart';
import '../providers/app_state.dart';
class PersonScreen extends StatelessWidget{final Person person;const PersonScreen({super.key,required this.person});@override Widget build(BuildContext context){final s=context.watch<AppState>();final l=AppLocalizations.of(context);return Scaffold(appBar:AppBar(title:Text(person.name)),body:FutureBuilder<Map<String,double>>(future:s.database.totals(s.currentLedger!.id!,personId:person.id),builder:(c,snap){final t=snap.data??{};return ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(title:Text(person.name,style:Theme.of(c).textTheme.titleLarge),subtitle:Text(person.phone),trailing:Text(l.money(t['net']??0,s.currentLedger!.currencyCode,CurrencyCatalog.byCode(s.currentLedger!.currencyCode).decimalDigits)))),Text(l.t('transactions'),style:Theme.of(c).textTheme.titleLarge),FutureBuilder<List<TransactionItem>>(future:s.database.transactions(s.currentLedger!.id!,personId:person.id),builder:(c,x)=>Column(children:(x.data??[]).map((q)=>ListTile(title:Text(q.description.isEmpty?q.type:q.description),subtitle:Text(l.date(q.date)),trailing:Text(l.money(q.amount,s.currentLedger!.currencyCode,CurrencyCatalog.byCode(s.currentLedger!.currencyCode).decimalDigits)))).toList()))]);}));}}
class PersonForm extends StatefulWidget{final int ledgerId;final Future<void> Function(Person) onSave;const PersonForm({super.key,required this.ledgerId,required this.onSave});@override State<PersonForm> createState()=>_PersonFormState();}
class _PersonFormState extends State<PersonForm>{final name=TextEditingController(),phone=TextEditingController();@override Widget build(BuildContext c){final l=AppLocalizations.of(c);return Scaffold(appBar:AppBar(title:Text(l.t('addPerson'))),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[TextField(controller:name,decoration:InputDecoration(labelText:l.t('name'))),const SizedBox(height:12),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:InputDecoration(labelText:l.t('phone'))),const Spacer(),SizedBox(width:double.infinity,child:FilledButton(onPressed:()async{if(name.text.trim().isEmpty)return;await widget.onSave(Person(ledgerId:widget.ledgerId,name:name.text.trim(),phone:phone.text.trim()));if(mounted)Navigator.pop(c);},child:Text(l.t('save'))))]));}}
Future<void> showTransactionForm(BuildContext c,AppState s,Person p,AppLocalizations l)async{final amount=TextEditingController(),desc=TextEditingController();String type='receivable';await showModalBottomSheet(context:c,isScrollControlled:true,builder:(_)=>Padding(padding:EdgeInsets.only(left:16,right:16,top:20,bottom:MediaQuery.of(c).viewInsets.bottom+20),child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField(value:type,items:[DropdownMenuItem(value:'receivable',child:Text(l.t('receivable'))),DropdownMenuItem(value:'payable',child:Text(l.t('payable'))),DropdownMenuItem(value:'received',child:Text(l.t('received'))),DropdownMenuItem(value:'paid',child:Text(l.t('paid')))],onChanged:(v)=>type=v!),TextField(controller:amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(labelText:l.t('amount'))),TextField(controller:desc,decoration:InputDecoration(labelText:l.t('description'))),const SizedBox(height:12),FilledButton(onPressed:(){final a=double.tryParse(amount.text.replaceAll(',',''));if(a==null||a<=0)return;s.addTx(TransactionItem(ledgerId:s.currentLedger!.id!,personId:p.id!,type:type,amount:a,date:DateTime.now(),description:desc.text));Navigator.pop(c);},child:Text(l.t('save')))])));}
